name: Run Postman Tests

on:
  schedule:
    - cron: '0 6 * * *'  # Ejecutar todos los días a las 6 AM UTC (ajusta según tu zona horaria)
  workflow_dispatch:  # Permite ejecución manual

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar
        run: npm install

      - name: Ejecutar colección de Postman
        run: newman run collection.json -e environment.json -r json --reporter-json-export report.json

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Ajusta la región de tu bucket

      - name: Subir resultados a S3
        run: aws s3 cp report.json s3://tu-bucket-de-s3/postman-reports/report-$(date +%F-%H%M).json
